# "java.lang.ClassNotFoundException "
# It means that a class is being referenced but not found. 
# It is usually caused by they referenced class not being at the referenced location, or on the same layer of the project file.
# Solved by adding "/home/antony/environments/n/" into this:
  export CLASSPATH=/home/antony/environments/n/stanford-corenlp-full-2018-10-05/stanford-corenlp-3.9.2.jar

# "Installation version issues: mkl-fft..."
pip2 install\
    numpy \
    scipy \
    pandas \
pvlib==0.6.0 \
    cloudpickle \
pickleshare \
    scikit-learn==0.20.0 \
python-dateutil==2.7.5 \
    matplotlib \
PyMySQL==0.9.2 \
mkl-fft \
mkl-random \
windrose==1.6.5 \
    Cython \
tables==3.4.4 \
pyrouge==0.1.3 \

# How to use the pretrain model: 
https://github.com/abisee/pointer-generator/issues/77

#Resource exhausted: OOM when allocating tensor with shape[16,512,273,1] and type float on /job:localhost/replica:
0/task:0/device:GPU:0 by allocator GPU_0_bfc python gpu.py (to grow gpu) max_enc_steps=40 max_dec_steps=10 (which 
is 1/10th of original size in run_summaraization.py)

# "Seq2Seq model decode error problem "Not found: Tensor name..."
# Solved by restoring directory path with original checkpoints:
--log_root=/home/antony/environments/n/cnn-dailymail/abstracter_model/ --exp_name=abstracter_model

#In the 'utils' folder, running 'data.py' gives an error. Referring to ln29, 'from config import utils', saying "no 
application named utils." Solve this by bringing 'data.py' to  root (i.e, n2 in this case) and run. Ln29 looks for a 
folder below root. So, if one modifies data.py's 'from config...' one can keep it inside the same folder.
